/*
 * This source file was generated by the Gradle 'init' task
 */
package ejercicio1;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("Grid Walking Simulation");
        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter number of test cases:");
        int testCases = scanner.nextInt();

        char[] finalDirections = new char[testCases];

        if(testCases >= 1 && testCases <= 100) {
            for (int i = 0; i < testCases; i++) {
                System.out.println("Test Case " + (i + 1) + ":");
                System.out.print("Enter grid rows: ");
                int rows = scanner.nextInt();
                System.out.print("Enter grid columns: ");
                int cols = scanner.nextInt();
                Grid grid = new Grid(rows, cols);
                grid.walkArroundGrid();
                finalDirections[i] = grid.getFinalDirection();
            }
        }

        System.out.println("Final Directions:");
        for (char direction : finalDirections) {
            System.out.println(direction);
        }

    }
}
